version: '3.4'

services:
  aspiredashboarddemo:
    image: ${DOCKER_REGISTRY-}aspiredashboarddemo
    build:
      context: .
      dockerfile: AspireDashboardDemo/Dockerfile
  aspiredashboard:
    image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard:8.0
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    ports:
      - "18888:18888"
      - "18889:18889"